export const ERROR_CODE = {
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    TEST_ACCESS_DENIED: "TEST_ACCESS_DENIED",
    TEST_NOT_AVAILABLE: "TEST_NOT_AVAILABLE",
    TEST_CLOSED: "TEST_CLOSED",
    PASSCODE_REQUIRED: "PASSCODE_REQUIRED",
    INCORRECT_PASSCODE: "INCORRECT_PASSCODE",
};
