const QUERY_KEYS = {
    GET_TEST: "get-test",
    GET_AVAILABLE_TAKERS: "get-available-takers",
    GET_TEST_SUBMISSION: "get-test-submission",
    GET_TEST_STATUS: "get-test-status",
    GET_SUBMISSION_ANSWERS: "get-test-answers",
    GET_CHAT: "get-chat",
    GET_CHATS: "get-chats",
    GET_AI_CHATS: "get-ai-chats",
    GET_MESSAGES: "get-messages",
    GET_ONLINE_USERS: "get-online-users",
    GET_BLOCKED_USERS: "get-blocked-users",
    GET_PASSCODE: "get-passcode",
    GET_TEST_SUBMISSIONS: "get-test-submissions",
};

const MUTATION_KEYS = {
    UPDATE_TEST: "update-test",
    VALIDATE_PARTS: "validate-parts",
    CREATE_TEST: "create-test",
    CREATE_PARTS: "create-parts",
    ADD_PART: "add-part",
    UPDATE_PART: "update-part",
    CREATE_QUESTION: "create-question",
    UPDATE_QUESTION: "update-question",
    DELETE_QUESTION: "delete-question",
    CREATE_TAKERS: "create-takers",
    ADD_TAKER: "add-taker",
    VALIDATE_QUESTIONS: "validate-questions",
    ADD_ANSWER: "add-answer",
    GENERATE_PASSCODE: "generate-passcode",
    CREATE_PASSCODE: "create-passcode",
    CHECK_PASSCODE: "check-passcode",
    SEND_MESSAGE: "send-message",
    UPDATE_MESSAGE: "update-message",
    DELETE_MESSAGE: "delete-message",
    UPDATE_CHAT: "update-chat",
    BLOCK_USER: "block-user",
    UNBLOCK_USER: "unblock-user",
    UPDATE_TAKER_ANSWER: "update-taker-answer",
    SUBMIT_ANSWERS: "submit-answers",
    REORDER_QUESTIONS: "reorder-questions",
    CREATE_CHAT: "create-chat",
};

export { QUERY_KEYS, MUTATION_KEYS };
