const QUERY_KEYS = {
    GET_TEST: "get-test",
    GET_AVAILABLE_TAKERS: "get-available-takers",
    GET_TEST_SUBMISSION: "get-test-submission",
    GET_TEST_STATUS: "get-test-status",
    GET_SUBMISSION_ANSWERS: "get-test-answers",
    GET_CHAT: "get-chat",
    GET_CHATS: "get-chats",
    GET_AI_CHATS: "get-ai-chats",
    GET_MESSAGES: "get-messages",
    GET_ONLINE_USERS: "get-online-users",
    GET_BLOCKED_USERS: "get-blocked-users",
    GET_PASSCODE: "get-passcode",
    GET_TEST_SUBMISSIONS: "get-test-submissions",
    GET_AI_MODELS: "get-ai-models",
    GET_TAKERS: "get-takers",
    GET_QUESTIONS_IN_BANK: "get-questions-in-bank",
    GET_TAKER_GROUPS: "get-taker-groups",
    GET_QUESTIONS_RESULT_FOR_TEST: "get-questions-result-for-test",
    GET_USERS_BY_EMAIL_SEARCH: "get-users-by-email-search",
    GET_MAKERS_WITH_GROUP: "get-makers-with-group",
};

const MUTATION_KEYS = {
    UPDATE_TEST: "update-test",
    VALIDATE_PARTS: "validate-parts",
    CREATE_TEST: "create-test",
    CREATE_PARTS: "create-parts",
    ADD_PART: "add-part",
    UPDATE_PART: "update-part",
    MOVE_PART: "move-part",
    CREATE_QUESTION: "create-question",
    UPDATE_QUESTION: "update-question",
    DELETE_QUESTION: "delete-question",
    CREATE_TAKERS: "create-takers",
    UPDATE_TAKER: "update-taker",
    ADD_TAKER: "add-taker",
    VALIDATE_QUESTIONS: "validate-questions",
    ADD_ANSWER: "add-answer",
    GENERATE_PASSCODE: "generate-passcode",
    CREATE_PASSCODE: "create-passcode",
    CHECK_PASSCODE: "check-passcode",
    SEND_MESSAGE: "send-message",
    UPDATE_MESSAGE: "update-message",
    DELETE_MESSAGE: "delete-message",
    UPDATE_CHAT: "update-chat",
    BLOCK_USER: "block-user",
    UNBLOCK_USER: "unblock-user",
    UPDATE_TAKER_ANSWER: "update-taker-answer",
    SUBMIT_ANSWERS: "submit-answers",
    REORDER_QUESTIONS: "reorder-questions",
    CREATE_CHAT: "create-chat",
    UPDATE_CHAT_AI: "update-chat-ai",
    CREATE_AI_CHAT: "create-ai-chat",
    DELETE_CHAT_AI: "delete-ai-chat",
    CREATE_QUESTION_IN_BANK: "create-question-in-bank",
    UPDATE_QUESTION_IN_BANK: "update-question-in-bank",
    DELETE_QUESTION_IN_BANK: "delete-question-in-bank",
    IMPORT_QUESTIONS_TO_BANK: "import-questions-to-bank",
    IMPORT_QUESTIONS_SUCCESSFULLY: "import-questions-successfully",
    DELETE_QUESTION_BANK: "delete-question-bank",
    CREATE_QUESTION_BANK: "create-question-bank",
    CREATE_TAKER_GROUP: "create-taker-group",
    UPDATE_USER: "update-user",
};

export { QUERY_KEYS, MUTATION_KEYS };
