export const SOCKET_EVENTS = {
    CONNECT: "connect",
    DISCONNECT: "disconnect",
    ONLINE: "online",
    GET_MESSAGE: "get-message",
    SEND_MESSAGE: "send-message",
    GET_CHATS: "get-chats",
    CREATE_CHAT: "create-chat",
    JOIN_CHAT: "join-chat",
    LEAVE_CHAT: "leave-chat",
    GET_ONLINE_USERS: "get-online-users",
    UPDATE_READ_MESSAGES: "update-read-messages",
    READ_MESSAGES: "read-messages",
    ADD_ONLINE_USERS: "add-online-users",
    SEND_ONLINE_USERS: "send-online-users",
    REMOVE_ONLINE_USERS: "remove-online-users",
    DELETE_MESSAGE: "delete-message",
    TYPING: "typing",
    STOP_TYPING: "stop-typing",
};
