export enum QUESTION_TYPE {
    MULTIPLE_CHOICES = "MULTIPLE_CHOICES",
    FILL_IN_THE_GAPS = "FILL_IN_THE_GAPS",
    MATCHING = "MATCHING",
    RESPONSE = "RESPONSE",
}

export const QUESTION_TYPE_LABEL: Record<QUESTION_TYPE, string> = {
    [QUESTION_TYPE.MULTIPLE_CHOICES]: "Multiple choices",
    [QUESTION_TYPE.FILL_IN_THE_GAPS]: "Fill in the gaps",
    [QUESTION_TYPE.MATCHING]: "Matching",
    [QUESTION_TYPE.RESPONSE]: "Response",
};

export enum CREATE_TEST_STEPS {
    TEST_INFORMATION = "TEST_INFORMATION",
    TEST_PARTS = "TEST_PARTS",
    TEST_QUESTIONS = "TEST_QUESTIONS",
    TEST_ANSWERS = "TEST_ANSWERS",
    TEST_TAKERS = "TEST_TAKERS",
}

export enum PUBLIC_ANSWER_VISIBILITY_LEVEL {
    SUMMARY = "SUMMARY",
    DETAILED = "DETAILED",
}
