const QUESTION_TYPE = {
    MULTIPLE_CHOICES: "MULTIPLE_CHOICES",
    FILL_IN_THE_GAPS: "FILL_IN_THE_GAPS",
    MATCHING: "MATCHING",
    RESPONSE: "RESPONSE",
};

const QUESTION_TYPE_LABEL = {
    [QUESTION_TYPE.MULTIPLE_CHOICES]: "Multiple choices",
    [QUESTION_TYPE.FILL_IN_THE_GAPS]: "Fill in the gaps",
    [QUESTION_TYPE.MATCHING]: "Matching",
    [QUESTION_TYPE.RESPONSE]: "Response",
};

const CREATE_TEST_STEPS = {
    TEST_INFORMATION: "TEST_INFORMATION",
    TEST_PARTS: "TEST_PARTS",
    TEST_QUESTIONS: "TEST_QUESTIONS",
    TEST_ANSWERS: "TEST_ANSWERS",
    TEST_TAKERS: "TEST_TAKERS",
};

export { QUESTION_TYPE, CREATE_TEST_STEPS, QUESTION_TYPE_LABEL };
