const QUESTION_TYPE = {
    MULTIPLE_CHOICES: "MULTIPLE_CHOICES",
    FILL_IN_THE_GAPS: "FILL_IN_THE_GAPS",
    MATCHING: "MATCHING",
    RESPONSE: "RESPONSE",
};

const CREATE_TEST_STEPS = {
    TEST_INFORMATION: "TEST_INFORMATION",
    TEST_PARTS: "TEST_PARTS",
    TEST_QUESTIONS: "TEST_QUESTIONS",
    TEST_ANSWERS: "TEST_ANSWERS",
    TEST_TAKERS: "TEST_TAKERS",
};

export { QUESTION_TYPE, CREATE_TEST_STEPS };
